apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  version: 1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
